var majors = [ { major: 'Accounting', credits: 23, elective: 53 },
  { major: 'Africana & Puerto Rican / Latino Studies',
    credits: 24,
    elective: 48 },
  { major: 'Ancient Greek', credits: 20, elective: 52 },
  { major: 'Anthropology ', credits: 17, elective: 52 },
  { major: 'Archaeology, Interdepartmental ',
    credits: 17,
    elective: 53 },
  { major: 'Art History', credits: 19, elective: 47 },
  { major: 'Behavioral Neurobiology', credits: 16, elective: 47 },
  { major: 'Bioinformatics (Quantitative Biology)',
    credits: 17,
    elective: 50 },
  { major: 'Biological Sciences with Specialization in Biotechnology',
    credits: 24,
    elective: 53 },
  { major: 'Biology ', credits: 18, elective: 51 },
  { major: 'Biology Adolescent Education',
    credits: 17,
    elective: 47 },
  { major: 'Biophysics', credits: 19, elective: 46 },
  { major: 'Chemistry', credits: 21, elective: 48 },
  { major: 'Chemistry Adolescent Education',
    credits: 21,
    elective: 48 },
  { major: 'Childhood Education (QUEST) 7',
    credits: 17,
    elective: 48 },
  { major: 'Chinese', credits: 20, elective: 51 },
  { major: 'Chinese Adolescent Education',
    credits: 15,
    elective: 46 },
  { major: 'Classical Studies ', credits: 19, elective: 45 },
  { major: 'Community Health', credits: 18, elective: 45 },
  { major: 'Comparative Literature', credits: 24, elective: 46 },
  { major: 'Computer Science', credits: 17, elective: 49 },
  { major: 'Creative Writing', credits: 20, elective: 53 },
  { major: 'Dance', credits: 22, elective: 49 },
  { major: 'Dance Education', credits: 21, elective: 51 },
  { major: 'Earth Science Adolescent Education',
    credits: 24,
    elective: 45 },
  { major: 'Economics', credits: 17, elective: 48 },
  { major: 'Environmental Studies', credits: 23, elective: 50 },
  { major: 'Film', credits: 22, elective: 54 },
  { major: 'French', credits: 24, elective: 52 },
  { major: 'French Adolescent Education',
    credits: 19,
    elective: 45 },
  { major: 'Geography', credits: 21, elective: 53 },
  { major: 'German', credits: 17, elective: 51 },
  { major: 'German Adolescent Education ',
    credits: 24,
    elective: 51 },
  { major: 'Hebrew ', credits: 15, elective: 46 },
  { major: 'Hebrew Adolescent Education',
    credits: 17,
    elective: 54 },
  { major: 'History ', credits: 22, elective: 51 },
  { major: 'Italian ', credits: 22, elective: 54 },
  { major: 'Italian Adolescent Education',
    credits: 24,
    elective: 51 },
  { major: 'Jewish Studies', credits: 22, elective: 51 },
  { major: 'Latin', credits: 18, elective: 54 },
  { major: 'Latin American and Caribbean Studies',
    credits: 15,
    elective: 51 },
  { major: 'Latin and Greek', credits: 19, elective: 45 },
  { major: 'Mathematics', credits: 21, elective: 53 },
  { major: 'Mathematics Adolescent Education',
    credits: 22,
    elective: 51 },
  { major: 'Media Studies', credits: 20, elective: 49 },
  { major: 'Medical Laboratory Sciences',
    credits: 23,
    elective: 49 },
  { major: 'Music', credits: 18, elective: 47 },
  { major: 'Music Education', credits: 17, elective: 50 },
  { major: 'Nursing, Accelerated Second-Degree Pathway',
    credits: 23,
    elective: 48 },
  { major: 'Nursing, Generic Pathway', credits: 23, elective: 45 },
  { major: 'Nursing, RN Pathway', credits: 17, elective: 49 },
  { major: 'Nutrition and Food Sciences',
    credits: 19,
    elective: 52 },
  { major: 'Philosophy', credits: 15, elective: 52 },
  { major: 'Philosophy, Politics and Society',
    credits: 16,
    elective: 53 },
  { major: 'Physics', credits: 22, elective: 54 },
  { major: 'Physics Adolescent Education',
    credits: 21,
    elective: 46 },
  { major: 'Political Science', credits: 24, elective: 53 },
  { major: 'Psychology', credits: 23, elective: 50 },
  { major: 'Psychology with Neuroscience Concentration',
    credits: 15,
    elective: 51 },
  { major: 'Religion', credits: 16, elective: 48 },
  { major: 'Romance Languages', credits: 24, elective: 49 },
  { major: 'Russian', credits: 18, elective: 53 },
  { major: 'Russian Adolescent Education',
    credits: 21,
    elective: 47 },
  { major: 'Social Studies Adolescent Education ',
    credits: 21,
    elective: 48 },
  { major: 'Sociology', credits: 22, elective: 45 },
  { major: 'Sociology and Social Research',
    credits: 18,
    elective: 54 },
  { major: 'Spanish Adolescent Education',
    credits: 24,
    elective: 49 },
  { major: 'Spanish and Latin American Literature',
    credits: 24,
    elective: 47 },
  { major: 'Spanish←→English Translation and Interpretation',
    credits: 23,
    elective: 50 },
  { major: 'Statistics', credits: 18, elective: 49 },
  { major: 'Statistics and Applied Mathematics',
    credits: 15,
    elective: 46 },
  { major: 'Studio Art', credits: 20, elective: 49 },
  { major: 'Theatre', credits: 19, elective: 50 },
  { major: 'Urban Studies', credits: 21, elective: 45 },
  { major: 'Women and Gender Studies', credits: 18, elective: 46 } ]

app.factory('majors', function(){
	return {
		getMajors: function(){
			return majors;
		}
	}
})